print("Hola primer GIT")
print("Hola primer GIT")
print("Hola primer GIT")
print("Hola primer GIT")
print("Hola primer GIT")
print("Hola primer GIT")
print("Hola primer GIT")
print("Hola primer DEV")
print("hola ")